# Generated by Django 4.2.7 on 2025-12-11 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('fire', 'Fire'), ('smoke', 'Smoke'), ('both', 'Fire & Smoke')], max_length=10)),
                ('confidence', models.FloatField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
